version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Docker/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_ADDR=redis:6379
    networks:
      - appnet

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks:
      - appnet

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./Docker/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
